#!/usr/bin/env bash
# Build Ostra, install the binary, and run it as a per-user service: a launchd agent on macOS, a systemd
# user unit on Linux. The service starts at login and restarts when the server fails.
#
# Usage:
#   ./install.sh [install] [ostra flags...]   build, install, and (re)start; for example --port 8080
#                                             The service listens on every interface unless a --bind
#                                             flag says otherwise, for example --bind 127.0.0.1
#   ./install.sh restart                      restart the service with the installed binary
#   ./install.sh status                       show whether the service runs
#   ./install.sh url                          print a fresh sign-in URL
#   ./install.sh uninstall                    stop and remove the service and the installed files
# Environment:
#   OSTRA_PREFIX     install prefix (default ~/.local; the binary goes to $OSTRA_PREFIX/bin)
#   OSTRA_ENV_FILE   credentials file whose `export` lines the service applies at every start
#   SKIP_BUILD=1     install the existing target/release/ostra without building
#   OSTRA_CONFIG, OSTRA_DATA_DIR   recorded into the service when set
set -euo pipefail
cd "$(dirname "$0")"
repo="$(pwd)"

prefix="${OSTRA_PREFIX:-$HOME/.local}"
bin_dir="$prefix/bin"
bin="$bin_dir/ostra"
launcher="$bin_dir/ostra-service"
label="dev.ostra.server"
plist="$HOME/Library/LaunchAgents/$label.plist"
unit_dir="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
unit="$unit_dir/ostra.service"

case "$(uname -s)" in
  Darwin) os=mac ;;
  Linux) os=linux ;;
  *) echo "Unsupported system $(uname -s). Use ./run.sh instead." >&2; exit 1 ;;
esac

if [[ -n "${OSTRA_DATA_DIR:-}" ]]; then
  data_dir="$OSTRA_DATA_DIR"
elif [[ $os == mac ]]; then
  data_dir="$HOME/Library/Application Support/ostra"
else
  data_dir="${XDG_DATA_HOME:-$HOME/.local/share}/ostra"
fi

xml_escape() {
  local s="$1"
  s="${s//&/&amp;}"; s="${s//</&lt;}"; s="${s//>/&gt;}"
  printf '%s' "$s"
}

# Writes the launcher the service runs. It applies the credentials file at every start, so a changed key
# needs only a restart, and the secrets stay out of the plist or unit file.
write_launcher() {
  local env_file="${OSTRA_ENV_FILE:-}"
  {
    echo '#!/usr/bin/env bash'
    echo '# Generated by install.sh in '"$repo"'. Rerun it to change these values.'
    echo 'set -euo pipefail'
    # Service managers start with a minimal PATH, so the installing shell's PATH is kept for harness CLIs.
    printf 'export PATH=%q\n' "$PATH"
    [[ -n "${OSTRA_CONFIG:-}" ]] && printf 'export OSTRA_CONFIG=%q\n' "$OSTRA_CONFIG"
    [[ -n "${OSTRA_DATA_DIR:-}" ]] && printf 'export OSTRA_DATA_DIR=%q\n' "$OSTRA_DATA_DIR"
    printf 'env_file=%q\n' "$env_file"
    cat <<'EOF'
if [[ -n "$env_file" && -f "$env_file" ]]; then
  # Only the `export NAME=value` lines are applied, so nothing else in the file runs.
  while IFS= read -r line; do
    eval "$line"
  done < <(grep -E '^[[:space:]]*export[[:space:]]+[A-Za-z_][A-Za-z0-9_]*=' "$env_file")
fi
EOF
    printf 'exec %q serve --no-open' "$bin"
    local a
    case " $* " in
      *" --bind "* | *" --bind="*) ;;
      *) printf ' --bind 0.0.0.0' ;;
    esac
    for a in "$@"; do printf ' %q' "$a"; done
    echo
  } > "$launcher.tmp"
  chmod 755 "$launcher.tmp"
  mv -f "$launcher.tmp" "$launcher"
  if [[ -n "$env_file" ]]; then
    echo "==> Credentials: the export lines of $env_file"
  else
    echo "==> No credentials file found; the service uses keys saved in Ostra or the keychain"
  fi
}

write_plist() {
  mkdir -p "$(dirname "$plist")"
  # stdout repeats server.log, so only stderr is kept, for panics and startup failures.
  cat > "$plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>$label</string>
  <key>ProgramArguments</key>
  <array><string>$(xml_escape "$launcher")</string></array>
  <key>WorkingDirectory</key><string>$(xml_escape "$HOME")</string>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key>
  <dict><key>SuccessfulExit</key><false/></dict>
  <key>ThrottleInterval</key><integer>10</integer>
  <key>ProcessType</key><string>Interactive</string>
  <key>StandardOutPath</key><string>/dev/null</string>
  <key>StandardErrorPath</key><string>$(xml_escape "$data_dir/service.err.log")</string>
</dict>
</plist>
EOF
}

write_unit() {
  mkdir -p "$unit_dir"
  # SIGINT is the signal the server shuts down gracefully on; SIGTERM would kill it mid-write.
  cat > "$unit" <<EOF
[Unit]
Description=Ostra engineering pipeline server
After=network-online.target

[Service]
Type=simple
ExecStart="$launcher"
WorkingDirectory=%h
KillSignal=SIGINT
TimeoutStopSec=20
Restart=on-failure
RestartSec=5
StandardOutput=null

[Install]
WantedBy=default.target
EOF
}

service_stop() {
  if [[ $os == mac ]]; then
    launchctl bootout "gui/$(id -u)/$label" 2>/dev/null || true
  else
    systemctl --user stop ostra.service 2>/dev/null || true
  fi
}

service_start() {
  if [[ $os == mac ]]; then
    service_stop
    # bootout returns before the job is gone, and bootstrap fails while it is still listed.
    local i
    for i in $(seq 1 20); do
      launchctl print "gui/$(id -u)/$label" >/dev/null 2>&1 || break
      sleep 0.5
    done
    launchctl bootstrap "gui/$(id -u)" "$plist"
  else
    systemctl --user daemon-reload
    systemctl --user enable ostra.service >/dev/null
    systemctl --user restart ostra.service
  fi
}

# server.json is rewritten at each start, so a copy newer than the marker belongs to the new process.
wait_and_print_url() {
  local marker="$1" i
  for i in $(seq 1 30); do
    if [[ -f "$data_dir/server.json" && "$data_dir/server.json" -nt "$marker" ]]; then
      rm -f "$marker"
      echo
      echo "Ostra is running. Open this URL to sign in (it works once; run \`ostra url\` for another):"
      echo
      echo "  $("$bin" url)"
      echo
      return
    fi
    sleep 0.5
  done
  rm -f "$marker"
  echo "The service did not report a running server within 15 seconds." >&2
  if [[ $os == mac ]]; then
    echo "Check $data_dir/service.err.log and $data_dir/server.log." >&2
  else
    echo "Check \`journalctl --user -u ostra\` and $data_dir/server.log." >&2
  fi
  exit 1
}

restart() {
  [[ -x "$launcher" ]] || { echo "Ostra is not installed. Run ./install.sh first." >&2; exit 1; }
  mkdir -p "$data_dir"
  local marker
  marker="$(mktemp)"
  # File times may have one-second resolution, so the new server.json must land a second later.
  sleep 1
  service_start
  wait_and_print_url "$marker"
}

install() {
  if [[ "${SKIP_BUILD:-}" != "1" ]]; then
    ./build.sh
  fi
  [[ -x target/release/ostra ]] || { echo "target/release/ostra is missing. Build it first." >&2; exit 1; }
  echo "==> Installing $bin"
  mkdir -p "$bin_dir" "$data_dir"
  # Replace by rename, so a running server keeps its binary and macOS does not kill it for a changed image.
  cp target/release/ostra "$bin.tmp"
  chmod 755 "$bin.tmp"
  mv -f "$bin.tmp" "$bin"
  write_launcher "$@"
  if [[ $os == mac ]]; then
    echo "==> Writing $plist"
    write_plist
  else
    echo "==> Writing $unit"
    write_unit
  fi
  echo "==> Starting the service"
  restart
  if ! grep -qE -- '--bind (127\.0\.0\.1|::1|localhost)( |$)' "$launcher"; then
    echo "Ostra listens on every interface over plain HTTP. Anyone who reaches the port with a sign-in link can"
    echo "run commands as you. Prefer an SSH tunnel or a TLS reverse proxy, or reinstall with --bind 127.0.0.1."
  fi
  case ":$PATH:" in
    *":$bin_dir:"*) ;;
    *) echo "Add $bin_dir to PATH to run \`ostra url\`, \`ostra stop\`, and the other commands." ;;
  esac
  if [[ $os == linux ]] && [[ "$(loginctl show-user "$USER" -p Linger --value 2>/dev/null)" != "yes" ]]; then
    echo "The service runs while you are logged in. To keep it running after logout: loginctl enable-linger $USER"
  fi
}

uninstall() {
  echo "==> Stopping the service"
  service_stop
  if [[ $os == mac ]]; then
    rm -f "$plist"
  else
    systemctl --user disable ostra.service 2>/dev/null || true
    rm -f "$unit"
    systemctl --user daemon-reload
  fi
  rm -f "$launcher" "$bin"
  echo "Removed the service and $bin. The config file and the data in $data_dir are kept."
}

status() {
  if [[ $os == mac ]]; then
    launchctl print "gui/$(id -u)/$label" 2>/dev/null | grep -E '^\t(state|pid|last exit code) =' \
      || echo "The service is not loaded."
  else
    systemctl --user status ostra.service --no-pager || true
  fi
}

cmd="${1:-install}"
case "$cmd" in
  install) shift || true; install "$@" ;;
  restart) restart ;;
  status) status ;;
  url) "$bin" url ;;
  uninstall) uninstall ;;
  -*) install "$@" ;;
  *) echo "Unknown command $cmd. Use install, restart, status, url, or uninstall." >&2; exit 1 ;;
esac
