//! The language table: comment and string syntax, keywords, and which family's definition and
//! import rules apply. One entry covers a language for display, outline, usages, and imports.

/// Languages that share definition and import rules.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Family {
    Rust,
    Js,
    Python,
    Go,
    /// Java, Kotlin, Scala, C#, Swift, and PHP: classes with members, dotted imports.
    Jvm,
    C,
    Ruby,
    Lua,
    Shell,
    /// Colored for display only: no definitions, no imports.
    Data,
}

#[derive(Debug)]
pub struct Lang {
    pub id: &'static str,
    pub family: Family,
    pub line_comments: &'static [&'static str],
    pub block_comment: Option<(&'static str, &'static str)>,
    pub nested_comments: bool,
    /// String delimiters. A backtick string always spans lines.
    pub quotes: &'static [u8],
    /// A `"` string may span lines.
    pub multiline_strings: bool,
    /// `"""` and `'''` strings.
    pub triple_quotes: bool,
    /// `'` starts a character literal only; Rust lifetimes are handled by the lexer.
    pub keywords: &'static [&'static str],
    pub case_insensitive: bool,
    pub types: &'static [&'static str],
    pub constants: &'static [&'static str],
    /// Characters an identifier may contain besides letters, digits, and `_`.
    pub ident_extra: &'static [u8],
    /// `@name` is an attribute or annotation.
    pub at_attributes: bool,
    /// Definition keywords and the kind of the name after them.
    pub defs: &'static [(&'static str, Def)],
}

/// What a definition keyword introduces.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Def {
    Function,
    Class,
    Enum,
    Interface,
    Type,
    Module,
    Constant,
    Variable,
    Macro,
    /// Rust `impl`, Swift `extension`: a container for the members inside, no new name.
    Impl,
}

impl Lang {
    /// Files of this language join the usages and dependency index.
    pub fn indexed(&self) -> bool {
        self.family != Family::Data
    }

    pub fn is_keyword(&self, word: &str) -> bool {
        if self.case_insensitive {
            self.keywords.iter().any(|k| k.eq_ignore_ascii_case(word))
        } else {
            self.keywords.contains(&word)
        }
    }

    pub fn def(&self, word: &str) -> Option<Def> {
        self.defs.iter().find(|(k, _)| *k == word).map(|(_, d)| *d)
    }
}

const C_COMMENT: Option<(&str, &str)> = Some(("/*", "*/"));

static RUST: Lang = Lang {
    id: "rust",
    family: Family::Rust,
    line_comments: &["//"],
    block_comment: C_COMMENT,
    nested_comments: true,
    quotes: b"\"",
    multiline_strings: true,
    triple_quotes: false,
    keywords: &[
        "as", "async", "await", "break", "const", "continue", "crate", "dyn", "else", "enum",
        "extern", "fn", "for", "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut",
        "pub", "ref", "return", "self", "static", "struct", "super", "trait", "type", "unsafe",
        "use", "where", "while", "yield", "union",
    ],
    case_insensitive: false,
    types: &[
        "bool", "char", "str", "u8", "u16", "u32", "u64", "u128", "usize", "i8", "i16", "i32",
        "i64", "i128", "isize", "f32", "f64", "Self",
    ],
    constants: &["true", "false", "None", "Some", "Ok", "Err"],
    ident_extra: b"",
    at_attributes: false,
    defs: &[
        ("fn", Def::Function),
        ("struct", Def::Class),
        ("union", Def::Class),
        ("enum", Def::Enum),
        ("trait", Def::Interface),
        ("type", Def::Type),
        ("mod", Def::Module),
        ("const", Def::Constant),
        ("static", Def::Constant),
        ("impl", Def::Impl),
    ],
};

const JS_KEYWORDS: &[&str] = &[
    "abstract",
    "as",
    "async",
    "await",
    "break",
    "case",
    "catch",
    "class",
    "const",
    "continue",
    "debugger",
    "declare",
    "default",
    "delete",
    "do",
    "else",
    "enum",
    "export",
    "extends",
    "finally",
    "for",
    "function",
    "if",
    "implements",
    "import",
    "in",
    "instanceof",
    "interface",
    "keyof",
    "let",
    "namespace",
    "new",
    "private",
    "protected",
    "public",
    "readonly",
    "return",
    "satisfies",
    "static",
    "super",
    "switch",
    "this",
    "throw",
    "try",
    "type",
    "typeof",
    "var",
    "void",
    "while",
    "with",
    "yield",
];

const JS_DEFS: &[(&str, Def)] = &[
    ("function", Def::Function),
    ("class", Def::Class),
    ("interface", Def::Interface),
    ("type", Def::Type),
    ("enum", Def::Enum),
    ("namespace", Def::Module),
    ("const", Def::Constant),
    ("let", Def::Variable),
    ("var", Def::Variable),
];

static TYPESCRIPT: Lang = Lang {
    id: "typescript",
    family: Family::Js,
    line_comments: &["//"],
    block_comment: C_COMMENT,
    nested_comments: false,
    quotes: b"\"'`",
    multiline_strings: false,
    triple_quotes: false,
    keywords: JS_KEYWORDS,
    case_insensitive: false,
    types: &[
        "string", "number", "boolean", "any", "unknown", "never", "object", "symbol", "bigint",
    ],
    constants: &["true", "false", "null", "undefined", "NaN", "Infinity"],
    ident_extra: b"$",
    at_attributes: true,
    defs: JS_DEFS,
};

static JAVASCRIPT: Lang = Lang {
    id: "javascript",
    types: &[],
    ..TYPESCRIPT
};

static PYTHON: Lang = Lang {
    id: "python",
    family: Family::Python,
    line_comments: &["#"],
    block_comment: None,
    nested_comments: false,
    quotes: b"\"'",
    multiline_strings: false,
    triple_quotes: true,
    keywords: &[
        "and", "as", "assert", "async", "await", "break", "class", "continue", "def", "del",
        "elif", "else", "except", "finally", "for", "from", "global", "if", "import", "in", "is",
        "lambda", "nonlocal", "not", "or", "pass", "raise", "return", "try", "while", "with",
        "yield", "match", "case",
    ],
    case_insensitive: false,
    types: &[
        "int", "float", "str", "bool", "bytes", "list", "dict", "set", "tuple", "object",
    ],
    constants: &["True", "False", "None"],
    ident_extra: b"",
    at_attributes: true,
    defs: &[("def", Def::Function), ("class", Def::Class)],
};

static GO: Lang = Lang {
    id: "go",
    family: Family::Go,
    line_comments: &["//"],
    block_comment: C_COMMENT,
    nested_comments: false,
    quotes: b"\"'`",
    multiline_strings: false,
    triple_quotes: false,
    keywords: &[
        "break",
        "case",
        "chan",
        "const",
        "continue",
        "default",
        "defer",
        "else",
        "fallthrough",
        "for",
        "func",
        "go",
        "goto",
        "if",
        "import",
        "interface",
        "map",
        "package",
        "range",
        "return",
        "select",
        "struct",
        "switch",
        "type",
        "var",
    ],
    case_insensitive: false,
    types: &[
        "bool",
        "byte",
        "complex64",
        "complex128",
        "error",
        "float32",
        "float64",
        "int",
        "int8",
        "int16",
        "int32",
        "int64",
        "rune",
        "string",
        "uint",
        "uint8",
        "uint16",
        "uint32",
        "uint64",
        "uintptr",
        "any",
    ],
    constants: &["true", "false", "nil", "iota"],
    ident_extra: b"",
    at_attributes: false,
    defs: &[
        ("func", Def::Function),
        ("type", Def::Type),
        ("const", Def::Constant),
        ("var", Def::Variable),
    ],
};

const JVM_MODIFIERS: &[&str] = &[
    "abstract",
    "final",
    "private",
    "protected",
    "public",
    "static",
    "override",
    "open",
    "internal",
    "sealed",
    "virtual",
    "readonly",
    "async",
    "partial",
    "data",
    "inline",
];

static JAVA: Lang = Lang {
    id: "java",
    family: Family::Jvm,
    line_comments: &["//"],
    block_comment: C_COMMENT,
    nested_comments: false,
    quotes: b"\"'",
    multiline_strings: false,
    triple_quotes: true,
    keywords: &[
        "abstract",
        "assert",
        "break",
        "case",
        "catch",
        "class",
        "continue",
        "default",
        "do",
        "else",
        "enum",
        "extends",
        "final",
        "finally",
        "for",
        "if",
        "implements",
        "import",
        "instanceof",
        "interface",
        "new",
        "package",
        "private",
        "protected",
        "public",
        "record",
        "return",
        "static",
        "super",
        "switch",
        "synchronized",
        "this",
        "throw",
        "throws",
        "try",
        "var",
        "void",
        "volatile",
        "while",
        "yield",
        "sealed",
        "permits",
    ],
    case_insensitive: false,
    types: &[
        "boolean", "byte", "char", "double", "float", "int", "long", "short",
    ],
    constants: &["true", "false", "null"],
    ident_extra: b"$",
    at_attributes: true,
    defs: &[
        ("class", Def::Class),
        ("interface", Def::Interface),
        ("enum", Def::Enum),
        ("record", Def::Class),
    ],
};

static KOTLIN: Lang = Lang {
    id: "kotlin",
    keywords: &[
        "as",
        "break",
        "by",
        "catch",
        "class",
        "companion",
        "continue",
        "data",
        "do",
        "else",
        "enum",
        "false",
        "for",
        "fun",
        "if",
        "import",
        "in",
        "init",
        "interface",
        "internal",
        "is",
        "object",
        "open",
        "override",
        "package",
        "private",
        "protected",
        "public",
        "return",
        "sealed",
        "super",
        "this",
        "throw",
        "try",
        "typealias",
        "val",
        "var",
        "when",
        "while",
        "suspend",
        "inline",
        "lateinit",
        "abstract",
        "final",
        "const",
    ],
    types: &[
        "Int", "Long", "Short", "Byte", "Double", "Float", "Boolean", "Char", "String", "Unit",
        "Any", "Nothing",
    ],
    defs: &[
        ("fun", Def::Function),
        ("class", Def::Class),
        ("interface", Def::Interface),
        ("object", Def::Class),
        ("typealias", Def::Type),
        ("val", Def::Variable),
        ("var", Def::Variable),
    ],
    ..JAVA
};

static SCALA: Lang = Lang {
    id: "scala",
    keywords: &[
        "abstract",
        "case",
        "catch",
        "class",
        "def",
        "do",
        "else",
        "extends",
        "final",
        "finally",
        "for",
        "given",
        "if",
        "implicit",
        "import",
        "lazy",
        "match",
        "new",
        "object",
        "override",
        "package",
        "private",
        "protected",
        "return",
        "sealed",
        "super",
        "this",
        "throw",
        "trait",
        "try",
        "type",
        "val",
        "var",
        "while",
        "with",
        "yield",
        "enum",
        "then",
    ],
    types: &[
        "Int", "Long", "Double", "Float", "Boolean", "Char", "String", "Unit", "Any",
    ],
    defs: &[
        ("def", Def::Function),
        ("class", Def::Class),
        ("object", Def::Class),
        ("trait", Def::Interface),
        ("enum", Def::Enum),
        ("type", Def::Type),
        ("val", Def::Variable),
        ("var", Def::Variable),
    ],
    ..JAVA
};

static CSHARP: Lang = Lang {
    id: "csharp",
    triple_quotes: false,
    keywords: &[
        "abstract",
        "as",
        "async",
        "await",
        "base",
        "break",
        "case",
        "catch",
        "class",
        "const",
        "continue",
        "default",
        "delegate",
        "do",
        "else",
        "enum",
        "event",
        "explicit",
        "extern",
        "finally",
        "fixed",
        "for",
        "foreach",
        "get",
        "if",
        "implicit",
        "in",
        "interface",
        "internal",
        "is",
        "lock",
        "namespace",
        "new",
        "operator",
        "out",
        "override",
        "params",
        "partial",
        "private",
        "protected",
        "public",
        "readonly",
        "record",
        "ref",
        "return",
        "sealed",
        "set",
        "sizeof",
        "static",
        "struct",
        "switch",
        "this",
        "throw",
        "try",
        "typeof",
        "unsafe",
        "using",
        "var",
        "virtual",
        "void",
        "volatile",
        "while",
        "yield",
    ],
    types: &[
        "bool", "byte", "char", "decimal", "double", "float", "int", "long", "object", "sbyte",
        "short", "string", "uint", "ulong", "ushort", "dynamic",
    ],
    ident_extra: b"",
    defs: &[
        ("class", Def::Class),
        ("struct", Def::Class),
        ("interface", Def::Interface),
        ("enum", Def::Enum),
        ("record", Def::Class),
        ("namespace", Def::Module),
    ],
    ..JAVA
};

static SWIFT: Lang = Lang {
    id: "swift",
    nested_comments: true,
    keywords: &[
        "as",
        "associatedtype",
        "break",
        "case",
        "catch",
        "class",
        "continue",
        "default",
        "defer",
        "deinit",
        "do",
        "else",
        "enum",
        "extension",
        "fallthrough",
        "fileprivate",
        "for",
        "func",
        "guard",
        "if",
        "import",
        "in",
        "init",
        "inout",
        "internal",
        "is",
        "let",
        "open",
        "operator",
        "private",
        "protocol",
        "public",
        "repeat",
        "return",
        "self",
        "static",
        "struct",
        "subscript",
        "super",
        "switch",
        "throw",
        "throws",
        "try",
        "typealias",
        "var",
        "where",
        "while",
        "async",
        "await",
        "override",
        "final",
        "mutating",
    ],
    types: &[
        "Int",
        "Double",
        "Float",
        "Bool",
        "String",
        "Character",
        "Void",
        "Any",
        "Self",
    ],
    constants: &["true", "false", "nil"],
    ident_extra: b"",
    defs: &[
        ("func", Def::Function),
        ("class", Def::Class),
        ("struct", Def::Class),
        ("enum", Def::Enum),
        ("protocol", Def::Interface),
        ("extension", Def::Impl),
        ("typealias", Def::Type),
        ("let", Def::Constant),
        ("var", Def::Variable),
    ],
    ..JAVA
};

static PHP: Lang = Lang {
    id: "php",
    line_comments: &["//", "#"],
    triple_quotes: false,
    keywords: &[
        "abstract",
        "and",
        "as",
        "break",
        "case",
        "catch",
        "class",
        "clone",
        "const",
        "continue",
        "declare",
        "default",
        "do",
        "echo",
        "else",
        "elseif",
        "enum",
        "extends",
        "final",
        "finally",
        "fn",
        "for",
        "foreach",
        "function",
        "global",
        "if",
        "implements",
        "include",
        "include_once",
        "instanceof",
        "interface",
        "match",
        "namespace",
        "new",
        "or",
        "private",
        "protected",
        "public",
        "readonly",
        "require",
        "require_once",
        "return",
        "static",
        "switch",
        "throw",
        "trait",
        "try",
        "use",
        "while",
        "yield",
    ],
    case_insensitive: false,
    types: &[
        "int", "float", "string", "bool", "array", "void", "mixed", "object", "self",
    ],
    constants: &["true", "false", "null", "TRUE", "FALSE", "NULL"],
    defs: &[
        ("function", Def::Function),
        ("class", Def::Class),
        ("interface", Def::Interface),
        ("trait", Def::Interface),
        ("enum", Def::Enum),
        ("namespace", Def::Module),
        ("const", Def::Constant),
    ],
    ..JAVA
};

static C: Lang = Lang {
    id: "c",
    family: Family::C,
    line_comments: &["//"],
    block_comment: C_COMMENT,
    nested_comments: false,
    quotes: b"\"'",
    multiline_strings: false,
    triple_quotes: false,
    keywords: &[
        "auto", "break", "case", "const", "continue", "default", "do", "else", "enum", "extern",
        "for", "goto", "if", "inline", "register", "restrict", "return", "sizeof", "static",
        "struct", "switch", "typedef", "union", "volatile", "while",
    ],
    case_insensitive: false,
    types: &[
        "char", "double", "float", "int", "long", "short", "signed", "unsigned", "void", "bool",
        "size_t", "int8_t", "int16_t", "int32_t", "int64_t", "uint8_t", "uint16_t", "uint32_t",
        "uint64_t",
    ],
    constants: &["true", "false", "NULL"],
    ident_extra: b"",
    at_attributes: false,
    defs: &[
        ("struct", Def::Class),
        ("union", Def::Class),
        ("enum", Def::Enum),
    ],
};

static CPP: Lang = Lang {
    id: "cpp",
    keywords: &[
        "alignas",
        "auto",
        "break",
        "case",
        "catch",
        "class",
        "const",
        "constexpr",
        "consteval",
        "continue",
        "decltype",
        "default",
        "delete",
        "do",
        "else",
        "enum",
        "explicit",
        "export",
        "extern",
        "final",
        "for",
        "friend",
        "goto",
        "if",
        "inline",
        "mutable",
        "namespace",
        "new",
        "noexcept",
        "operator",
        "override",
        "private",
        "protected",
        "public",
        "return",
        "sizeof",
        "static",
        "struct",
        "switch",
        "template",
        "this",
        "throw",
        "try",
        "typedef",
        "typename",
        "union",
        "using",
        "virtual",
        "volatile",
        "while",
        "co_await",
        "co_return",
    ],
    constants: &["true", "false", "nullptr", "NULL"],
    defs: &[
        ("struct", Def::Class),
        ("class", Def::Class),
        ("union", Def::Class),
        ("enum", Def::Enum),
        ("namespace", Def::Module),
    ],
    ..C
};

static RUBY: Lang = Lang {
    id: "ruby",
    family: Family::Ruby,
    line_comments: &["#"],
    block_comment: None,
    nested_comments: false,
    quotes: b"\"'`",
    multiline_strings: true,
    triple_quotes: false,
    keywords: &[
        "alias",
        "and",
        "begin",
        "break",
        "case",
        "class",
        "def",
        "defined?",
        "do",
        "else",
        "elsif",
        "end",
        "ensure",
        "for",
        "if",
        "in",
        "module",
        "next",
        "not",
        "or",
        "redo",
        "rescue",
        "retry",
        "return",
        "self",
        "super",
        "then",
        "undef",
        "unless",
        "until",
        "when",
        "while",
        "yield",
        "require",
        "require_relative",
        "attr_reader",
        "attr_accessor",
    ],
    case_insensitive: false,
    types: &[],
    constants: &["true", "false", "nil"],
    ident_extra: b"?!",
    at_attributes: false,
    defs: &[
        ("def", Def::Function),
        ("class", Def::Class),
        ("module", Def::Module),
    ],
};

static LUA: Lang = Lang {
    id: "lua",
    family: Family::Lua,
    line_comments: &["--"],
    block_comment: Some(("--[[", "]]")),
    nested_comments: false,
    quotes: b"\"'",
    multiline_strings: false,
    triple_quotes: false,
    keywords: &[
        "and", "break", "do", "else", "elseif", "end", "for", "function", "goto", "if", "in",
        "local", "not", "or", "repeat", "return", "then", "until", "while",
    ],
    case_insensitive: false,
    types: &[],
    constants: &["true", "false", "nil"],
    ident_extra: b"",
    at_attributes: false,
    defs: &[("function", Def::Function)],
};

static SHELL: Lang = Lang {
    id: "shell",
    family: Family::Shell,
    line_comments: &["#"],
    block_comment: None,
    nested_comments: false,
    quotes: b"\"'`",
    multiline_strings: true,
    triple_quotes: false,
    keywords: &[
        "if", "then", "else", "elif", "fi", "case", "esac", "for", "while", "until", "do", "done",
        "in", "function", "select", "return", "exit", "local", "export", "readonly", "declare",
        "source",
    ],
    case_insensitive: false,
    types: &[],
    constants: &["true", "false"],
    ident_extra: b"",
    at_attributes: false,
    defs: &[("function", Def::Function)],
};

static SQL: Lang = Lang {
    id: "sql",
    family: Family::Data,
    line_comments: &["--"],
    block_comment: C_COMMENT,
    nested_comments: false,
    quotes: b"'\"",
    multiline_strings: true,
    triple_quotes: false,
    keywords: &[
        "select",
        "from",
        "where",
        "insert",
        "into",
        "values",
        "update",
        "set",
        "delete",
        "create",
        "table",
        "index",
        "view",
        "drop",
        "alter",
        "add",
        "column",
        "primary",
        "key",
        "foreign",
        "references",
        "not",
        "null",
        "and",
        "or",
        "join",
        "left",
        "right",
        "inner",
        "outer",
        "on",
        "group",
        "by",
        "order",
        "having",
        "limit",
        "offset",
        "as",
        "distinct",
        "union",
        "all",
        "exists",
        "in",
        "is",
        "like",
        "case",
        "when",
        "then",
        "else",
        "end",
        "default",
        "unique",
        "if",
        "begin",
        "commit",
        "rollback",
        "transaction",
        "with",
        "returning",
        "trigger",
        "virtual",
        "using",
    ],
    case_insensitive: true,
    types: &[
        "integer",
        "int",
        "text",
        "real",
        "blob",
        "boolean",
        "varchar",
        "char",
        "numeric",
        "timestamp",
        "date",
        "bigint",
        "serial",
        "json",
        "jsonb",
    ],
    constants: &["TRUE", "FALSE", "true", "false"],
    ident_extra: b"",
    at_attributes: false,
    defs: &[],
};

static TOML: Lang = Lang {
    id: "toml",
    family: Family::Data,
    line_comments: &["#"],
    block_comment: None,
    nested_comments: false,
    quotes: b"\"'",
    multiline_strings: false,
    triple_quotes: true,
    keywords: &[],
    case_insensitive: false,
    types: &[],
    constants: &["true", "false"],
    ident_extra: b"-",
    at_attributes: false,
    defs: &[],
};

static YAML: Lang = Lang {
    id: "yaml",
    triple_quotes: false,
    constants: &["true", "false", "null", "yes", "no", "~"],
    ..TOML
};

static JSON: Lang = Lang {
    id: "json",
    line_comments: &[],
    quotes: b"\"",
    triple_quotes: false,
    constants: &["true", "false", "null"],
    ident_extra: b"",
    ..TOML
};

static CSS: Lang = Lang {
    id: "css",
    family: Family::Data,
    line_comments: &[],
    block_comment: C_COMMENT,
    nested_comments: false,
    quotes: b"\"'",
    multiline_strings: false,
    triple_quotes: false,
    keywords: &[
        "important",
        "media",
        "import",
        "keyframes",
        "supports",
        "layer",
    ],
    case_insensitive: false,
    types: &[],
    constants: &[],
    ident_extra: b"-",
    at_attributes: false,
    defs: &[],
};

static HTML: Lang = Lang {
    id: "html",
    line_comments: &[],
    block_comment: Some(("<!--", "-->")),
    keywords: &[],
    ..CSS
};

/// Every language, for lookups by id.
pub static ALL: &[&Lang] = &[
    &RUST,
    &TYPESCRIPT,
    &JAVASCRIPT,
    &PYTHON,
    &GO,
    &JAVA,
    &KOTLIN,
    &SCALA,
    &CSHARP,
    &SWIFT,
    &PHP,
    &C,
    &CPP,
    &RUBY,
    &LUA,
    &SHELL,
    &SQL,
    &TOML,
    &YAML,
    &JSON,
    &CSS,
    &HTML,
];

/// The language of a project-relative path, from its extension or file name.
pub fn for_path(path: &str) -> Option<&'static Lang> {
    let name = path.rsplit('/').next().unwrap_or(path);
    match name {
        "Makefile" | "Dockerfile" => return None,
        "Gemfile" | "Rakefile" => return Some(&RUBY),
        ".bashrc" | ".zshrc" | ".profile" => return Some(&SHELL),
        _ => {}
    }
    let ext = name.rsplit_once('.')?.1.to_ascii_lowercase();
    Some(match ext.as_str() {
        "rs" => &RUST,
        "ts" | "tsx" | "mts" | "cts" => &TYPESCRIPT,
        "js" | "jsx" | "mjs" | "cjs" => &JAVASCRIPT,
        "py" | "pyi" => &PYTHON,
        "go" => &GO,
        "java" => &JAVA,
        "kt" | "kts" => &KOTLIN,
        "scala" | "sc" => &SCALA,
        "cs" => &CSHARP,
        "swift" => &SWIFT,
        "php" => &PHP,
        "c" | "h" => &C,
        "cc" | "cpp" | "cxx" | "hpp" | "hh" | "hxx" | "ipp" | "m" | "mm" => &CPP,
        "rb" | "rake" | "gemspec" => &RUBY,
        "lua" => &LUA,
        "sh" | "bash" | "zsh" => &SHELL,
        "sql" => &SQL,
        "toml" => &TOML,
        "yaml" | "yml" => &YAML,
        "json" | "jsonc" => &JSON,
        "css" | "scss" | "less" => &CSS,
        "html" | "htm" | "xml" | "svg" | "vue" | "svelte" => &HTML,
        _ => return None,
    })
}

pub fn by_id(id: &str) -> Option<&'static Lang> {
    ALL.iter().copied().find(|l| l.id == id)
}

/// Modifiers that may stand between a definition's start and its name in class bodies.
pub fn is_modifier(word: &str) -> bool {
    JVM_MODIFIERS.contains(&word)
}
