import {
  Activity,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  BookCheck,
  BookOpen,
  Box,
  Braces,
  Brain,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronsDownUp,
  ChevronsUpDown,
  CircleAlert,
  CircleCheck,
  CircleMinus,
  CirclePause,
  CircleX,
  Coins,
  Copy,
  CornerDownRight,
  CornerLeftUp,
  Database,
  Eye,
  EyeOff,
  File,
  FileBraces,
  FileCheck,
  FileCodeCorner,
  FileCog,
  FileDiff,
  FileLock,
  FilePlus,
  Files,
  FileText,
  Flag,
  Folder,
  FolderGit2,
  FolderOpen,
  FolderPlus,
  FolderSearch,
  FolderTree,
  FolderX,
  GitBranch,
  GitCommitHorizontal,
  GitFork,
  GitPullRequest,
  Globe,
  GraduationCap,
  Hand,
  Info,
  Kanban,
  LayoutDashboard,
  LifeBuoy,
  List,
  ListChecks,
  ListFilter,
  ListTree,
  LocateFixed,
  type LucideIcon,
  Maximize2,
  MessageCircleQuestionMark,
  MessageSquare,
  Minimize2,
  Minus,
  Moon,
  OctagonAlert,
  OctagonX,
  Package,
  PanelLeft,
  PanelRight,
  Pencil,
  PencilLine,
  Play,
  PlugZap,
  Plus,
  RefreshCcw,
  Repeat,
  RotateCcw,
  Scale,
  Scan,
  Search,
  Settings,
  Shapes,
  ShieldAlert,
  ShieldCheck,
  Sparkles,
  Square,
  SquareFunction,
  SquareTerminal,
  Sun,
  SunMoon,
  Terminal,
  TextSearch,
  Trash2,
  TriangleAlert,
  Workflow,
  Wrench,
  X,
  ZoomIn,
  ZoomOut,
} from "lucide-react";

/**
 * Every icon the design uses, keyed by its Lucide kebab-case name. An explicit map keeps the bundle to
 * these glyphs; add an entry here before using a new name.
 */
export const ICONS = {
  scan: Scan,
  shapes: Shapes,
  "square-function": SquareFunction,
  workflow: Workflow,
  "zoom-in": ZoomIn,
  "zoom-out": ZoomOut,
  activity: Activity,
  "arrow-down": ArrowDown,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  "book-check": BookCheck,
  "book-open": BookOpen,
  box: Box,
  braces: Braces,
  brain: Brain,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  "chevrons-down-up": ChevronsDownUp,
  "chevrons-up-down": ChevronsUpDown,
  "circle-alert": CircleAlert,
  "circle-check": CircleCheck,
  "circle-minus": CircleMinus,
  "circle-pause": CirclePause,
  "circle-x": CircleX,
  coins: Coins,
  copy: Copy,
  "corner-down-right": CornerDownRight,
  "corner-left-up": CornerLeftUp,
  database: Database,
  eye: Eye,
  "eye-off": EyeOff,
  file: File,
  "file-check": FileCheck,
  "file-code-2": FileCodeCorner,
  "file-cog": FileCog,
  "file-diff": FileDiff,
  "file-json": FileBraces,
  "file-lock": FileLock,
  "file-plus": FilePlus,
  "file-text": FileText,
  files: Files,
  flag: Flag,
  folder: Folder,
  "folder-git-2": FolderGit2,
  "folder-open": FolderOpen,
  "folder-plus": FolderPlus,
  "folder-search": FolderSearch,
  "folder-tree": FolderTree,
  "folder-x": FolderX,
  "git-branch": GitBranch,
  "git-commit-horizontal": GitCommitHorizontal,
  "git-fork": GitFork,
  "git-pull-request": GitPullRequest,
  globe: Globe,
  "graduation-cap": GraduationCap,
  hand: Hand,
  info: Info,
  kanban: Kanban,
  "layout-dashboard": LayoutDashboard,
  "life-buoy": LifeBuoy,
  list: List,
  "list-checks": ListChecks,
  "list-filter": ListFilter,
  "list-tree": ListTree,
  "locate-fixed": LocateFixed,
  "message-circle-question": MessageCircleQuestionMark,
  "message-square": MessageSquare,
  "maximize-2": Maximize2,
  "minimize-2": Minimize2,
  minus: Minus,
  moon: Moon,
  "octagon-alert": OctagonAlert,
  "octagon-x": OctagonX,
  "panel-left": PanelLeft,
  "panel-right": PanelRight,
  package: Package,
  pencil: Pencil,
  "pencil-line": PencilLine,
  play: Play,
  "plug-zap": PlugZap,
  plus: Plus,
  "refresh-ccw": RefreshCcw,
  repeat: Repeat,
  "rotate-ccw": RotateCcw,
  scale: Scale,
  search: Search,
  settings: Settings,
  "shield-alert": ShieldAlert,
  "shield-check": ShieldCheck,
  sparkles: Sparkles,
  square: Square,
  "square-terminal": SquareTerminal,
  sun: Sun,
  "sun-moon": SunMoon,
  terminal: Terminal,
  "trash-2": Trash2,
  "text-search": TextSearch,
  "triangle-alert": TriangleAlert,
  wrench: Wrench,
  x: X,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

export const ICON_NAMES = Object.keys(ICONS) as IconName[];
